# Generated by Django 5.0.2 on 2026-01-05 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AIModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(help_text='Is the AI prediction correct?')),
                ('corrected_has_caries', models.BooleanField(blank=True, null=True)),
                ('corrected_severity', models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50, null=True)),
                ('feedback_text', models.TextField(blank=True, help_text='Additional comments or observations')),
                ('corrected_boxes', models.JSONField(blank=True, help_text='Corrected or additional bounding boxes', null=True)),
                ('ai_performance_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rate AI accuracy (1=Poor, 5=Excellent)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_findings', models.TextField(blank=True, help_text='Clinical examination findings')),
                ('recommended_treatment', models.TextField(blank=True, help_text='Recommended treatment plan')),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('low', 'Low Confidence - Needs Second Opinion')], default='high', max_length=20)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Has this feedback been reviewed by senior dentist?')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_feedbacks', to='AIModel.diagnosisresult')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dentist Feedback',
                'verbose_name_plural': 'Dentist Feedbacks',
                'db_table': 'dentist_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feedback_attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('other', 'Other')], default='image', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dentist_feedback.dentistfeedback')),
            ],
            options={
                'db_table': 'dentist_feedback_attachment',
            },
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('false_positive', 'False Positive'), ('false_negative', 'False Negative'), ('severity_mismatch', 'Severity Mismatch'), ('location_inaccurate', 'Location Inaccurate'), ('excellent_detection', 'Excellent Detection'), ('image_quality_issue', 'Image Quality Issue'), ('artifact_detected', 'Artifact Detected as Caries'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dentist_feedback.dentistfeedback')),
            ],
            options={
                'verbose_name_plural': 'Feedback Categories',
                'db_table': 'dentist_feedback_category',
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dentist_feedback.dentistfeedback')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dentist_feedback.feedbackcomment')),
            ],
            options={
                'db_table': 'dentist_feedback_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_diagnoses', models.IntegerField(default=0)),
                ('total_feedback', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('severity_metrics', models.JSONField(default=dict)),
                ('category_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'dentist_feedback_performance_metric',
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['-calculated_at'], name='dentist_fee_calcula_402b46_idx'), models.Index(fields=['period_start', 'period_end'], name='dentist_fee_period__f900a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ValidationStatus',
            fields=[
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='validation_info', serialize=False, to='AIModel.diagnosisresult')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_priority', models.IntegerField(default=0, help_text='Higher number = higher priority for review')),
                ('is_flagged', models.BooleanField(default=False, help_text='Flag for urgent review')),
                ('flag_reason', models.TextField(blank=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Status',
                'verbose_name_plural': 'Validation Statuses',
                'db_table': 'dentist_feedback_validation_status',
            },
        ),
        migrations.AddIndex(
            model_name='dentistfeedback',
            index=models.Index(fields=['diagnosis', '-created_at'], name='dentist_fee_diagnos_220902_idx'),
        ),
        migrations.AddIndex(
            model_name='dentistfeedback',
            index=models.Index(fields=['dentist', '-created_at'], name='dentist_fee_dentist_544a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='dentistfeedback',
            index=models.Index(fields=['is_correct'], name='dentist_fee_is_corr_9b3802_idx'),
        ),
    ]
