# Generated by Django 5.0.2 on 2025-12-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
