# Generated by Django 5.0.2 on 2026-01-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIModel', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='dentist_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.patient'),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='verified_by_dentist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dental_images/'),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
