# Generated by Django 5.0.2 on 2026-01-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIModel', '0002_diagnosisresult_dentist_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='gradcam_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='xai_explanation_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='xai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='xai_overlay_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
