# Generated by Django 5.0.2 on 2026-01-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIModel', '0003_diagnosisresult_gradcam_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='gradcam_url',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='xai_explanation_url',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='xai_generated_at',
        ),
        migrations.RemoveField(
            model_name='diagnosisresult',
            name='xai_overlay_url',
        ),
    ]
