# Generated by Django 5.0.2 on 2026-01-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIModel', '0004_remove_diagnosisresult_gradcam_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosisresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('preprocessing', 'Preprocessing'), ('preprocessed', 'Preprocessed'), ('detecting', 'Detecting'), ('detected', 'Detected'), ('classifying', 'Classifying'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
