# Generated by Django 6.0.3 on 2026-05-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIModel', '0007_alter_diagnosisresult_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisresult',
            name='all_probabilities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisresult',
            name='class_labels',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
